### ISSUE TITLE
Probably google bot

### ISSUE THREAD

**Issue by danon** [JayBizzle/Crawler-Detect#524] opened 2024-04-08 18:47 UTC
I'm receving high traffic from this user agent:
```
Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.6261.94 Mobile Safari/537.36 (compatible; GoogleOther)
```

and that's probably google bot, as I can see here: https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers#common-crawlers

**Comment by BartVB** [comment] 2024-04-10 07:41
This is a duplicate of #505

**Closed** 2024-04-10 07:43 UTC
